#!/bin/sh
export GOPATH=~/bin/submodules/go/
go get -d -u github.com/google/battery-historian/...
cd $GOPATH/src/github.com/google/battery-historian
go run cmd/battery-historian/battery-historian.go "$@"
