#!/usr/local/bin/zsh
trap 'exit 1' INT

set -eux

flags="bPvU"
build=
ports=1
rebuild=1
verbose=
while getopts "$flags" flag
do
  case "$flag" in
  b)  build=1  ;;
  U)  rebuild= ;;
  P)  ports= ;;
  v)  verbose=1  ;;
  ?)  printf "Usage: %s: [-%s] ...\\n" "$0" "$flags"
      exit 2;;
  esac
done

shift $((OPTIND-1))

if [[ -n "$verbose" ]]
then
  set -v
fi

if [ -n "$build" ]
then
  (
    sudo beadm create rebuild-pre-"$(date +%F-%H-%M-%S)" &&
    cd /usr/src &&
    svn up &&
    make -s buildworld buildkernel -j34 KERNCONF=EADLER &&
    sudo make -s installworld installkernel -j64 KERNCONF=EADLER &&
    sudo make -s delete-old &&
    sudo beadm create rebuild-post-"$(date +%F-%H-%M-%S)"
  )
fi

if [ -n "$rebuild" ]
then
  sudo poudriere jail -j amd64-matches-host -u
fi
if [ -n "$ports" ]
then
  (cd /srv/src/freebsd/ports && git pull)
  sudo poudriere bulk -j amd64-matches-host -p development $(pkg query -e '%a=0' '%o')
fi
sudo pkg upgrade
