#!/bin/sh
. ~/bin/.lib/git-lib

masterbranch="$(git_master_branch)"

b="$1"

if [ -z "$b" ]
then
  echo "$0 <commit>"
  exit 1
fi

git checkout -b eax/br/$b "origin/$masterbranch";
if git cherry-pick "$b"
then
  git push grimreaper;
  EDITOR=cat hub pull-request;
else
  git cherry-pick --abort
fi
