#!/usr/bin/env zsh

. ~/bin/.lib/git-lib

masterbranch="$(git_master_branch)"
while getopts b: flag
do
  case "$flag" in
  b)  masterbranch="$OPTARG" ;;
  ?)  printf "Usage: %s: [-b branch] ...\n" "$0"
      exit 2;;
  esac
done

branches="$(git for-each-ref --merged="$masterbranch" --format="%(refname:short)" refs/heads|grep -v ${masterbranch##origin/})"
if [[ -n "$branches" ]]
then
  git for-each-ref --merged="$masterbranch" --format="%(refname:short)" refs/heads|grep -v ${masterbranch##origin/} | xargs git branch -d;
fi

