#!/bin/sh
set -eux

git fetch --all --prune
git for-each-ref --format='%(refname:short) %(upstream:short)' refs/heads | while read -r branch upstream
do
  if [ -z "$upstream" ]; then
    continue
  fi
  behind="$(git rev-list --use-bitmap-index --count "$upstream..$branch")"
  if [ "$behind" -eq 0 ]; then
    continue
  fi
  ahead="$(git rev-list --use-bitmap-index --count "$branch..$upstream")"
  if [ "$ahead" -eq 0 ]; then
    continue
  fi
  git checkout "$branch"
  rebase_action="$upstream"
  while ! git rebase "$rebase_action"
  do
    if git diff-index --quiet HEAD --
    then
      git rebase --skip
      rebase_action="--continue"
    else
      rebase_action="--abort"
    fi
  done
done
git checkout master
git branch --merged=origin/master|grep -v master|xargs git branch -d
