#!/bin/sh
set -eux

git fetch --all --prune
for branch in $(git for-each-ref --format='%(refname:short)' refs/heads)
do
  git checkout $branch
  tracking=$(git for-each-ref --format="%(upstream:short)" $(git symbolic-ref -q HEAD))
  git rebase "$tracking" || git rebase --abort
done
git branch --merged=origin/master|grep -v master|xargs git branch -d
