#!/bin/sh

set -eux

base_cmd="java -Xmx2000m -jar"
cmd=$(basename "$0")

case "$cmd" in 
  "hexographer")
  ;;
  "dungeonographer")
  ;;
  "cityographer")
  ;;
  *)
    echo "invalid base name" >&2
    exit 1
  ;;
esac

exec $base_cmd ~/Dropbox/applications/rpg-applications/$cmd.jar
