#!/bin/sh
if [ ! -e ~/bin/submodules/go/bin/hugo ]
then
  (
    export GOPATH=~/bin/submodules/go/
    CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest
  )
fi
~/bin/submodules/go/bin/hugo "$@"
