#!/bin/sh
#/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend
#open -a /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app
osascript -e 'tell application \"System Events\" to keystroke \"q\" using {command down,control down}'"
