#!/bin/sh

endpoint="${PB_ENDPOINT:-https://ptpb.pw}"
private="${PB_PRIVATE:-0}"

pb_ () {
  filename="${1:--}"; shift;

  curl -s -F "c=@$filename" -F "p=$private" \
       "$@" "$endpoint"
}

case "$1" in
    private)
      shift
      private=1
      pb_ "$@"
      ;;
    *)
      pb_ "$@"
      ;;
esac
