#!/usr/bin/env python3
import argparse
import sys

parser = argparse.ArgumentParser(description="Process some numbers")
parser.add_argument("value", type=str, nargs=1, help="translated number")
args = parser.parse_args()

number = eval(args.value[0])

print("dec: ", format(number, "d"))
print("hex: ", format(number, "X"))
print("oct: ", format(number, "o"))
print("bin: ", format(number, "b"))
