#!/bin/sh
. ~/.conf/common_shell/functions.sh

set -- $(getopt -n "$0" -o "h:" -l "host:" -- "$@")

for o
do case "$o" in
	-h|--host)
		shift; host="$1"; shift;
		;;
	esac
done

host="${host:?host required}"

export AUTOSSH_DEBUG=1
cmd="autossh -S none -vvv -M 5656 -N -D 5554 $host -N -vvv"
if __exists tmux
then
	tmux new-session -d -s "ssh-tunnels-$host" -n "ssh-tunnel-$host" "reattach-to-user-namespace $cmd"
else
  $cmd
fi
