#!/bin/zsh
setopt extendedglob
set -v
dir=$(mktemp -d)
curl -o "$dir/out.dmg" -L https://calibre-ebook.com/dist/osx
for old in /Volumes/calibre-*(N)
do
	hdiutil detach "$old"
done
hdiutil attach $dir/out.dmg 
cd /Volumes/calibre-*
cp -a calibre.app /Applications/calibre.app
hdiutil detach /Volumes/calibre-*
