#!/bin/sh
set -x

quit() {
  exit 1
}

trap quit INT

selfupdate=1
while getopts s flag
do
  case "$flag" in
  s)  selfupdate= ;;
  ?)  printf "Usage: %s: [-s] ...\n" "$0"
      exit 2;;
  esac
done

shift "$((OPTIND - 1))"

for repo in ~/bin ~/misc-scripts ~/.conf
do
  (
    cd "$repo" &&
    git pull --rebase &&
    git submodule update --init --recursive &&
    git push
    )
done

if [ -n "$selfupdate" ]
then
  exec "$0" -s "$@";
fi

(cd ~/bin && ./submodules/update.sh)

while true; do sudo -v; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
sudo -H port selfupdate
port outdated
sudo -H port -u upgrade outdated
printf "y\nd\n"|sudo -H port reclaim
sudo -H pkg upgrade
sudo -H apt-get update
sudo -H apt-get dist-upgrade
gem update --user-install
sudo npm -g update
apm update
pip install --user -U $(pip list --format=legacy --outdated | awk '!/Could not|ignored/ {print $1}')
#cpan -u
vim -i NONE +PlugUpgrade +qa
(cd ~/.conf && git commit -m "Update VimPlug config" vim/home/autoload/plug.vim && git push)
vim -i NONE +PlugUpdate +PlugClean! +qa
rustup update
rustup self update
cargo search # update registry
stack upgrade
stack update
softwareupdate -i -a
mas upgrade
