#!/bin/sh
set -x

quit() {
  exit 1
}

__exists () {
  while [ -n "$1" ];
  do
    cmd="$1"; shift
    which "$cmd" >/dev/null 2>&1 || return 1
  done
  return 0;
}

__sudo() {
  if [ -n "$doroot" ]
  then
    sudo -H "$@"
  fi
}

trap quit INT

config_only=
mac=1
selfupdate=1
doroot=1
freebsd=1
while getopts cFMRS flag
do
  case $flag in
  c)  config_only=1
    ;;
  F)  freebsd= ;;
  R)  doroot= ;;
  M)  mac= ;;
  S)  selfupdate= ;;
  ?)  printf "Usage: %s: [-cMRS] ...\n" "$0"
      exit 2;;
  esac
done

for repo in ~/bin ~/misc-scripts ~/.conf ~/global
do
  (
    cd "$repo" &&
    git pull --rebase &&
    git submodule update --init --recursive &&
    git push
    )
done

if [ -n "$selfupdate" ]
then
  exec "$0" -S "$@";
fi

(cd ~/bin && ./submodules/update.sh)

if [ -n "$config_only"  ]
then
  exit 0
fi

_pip_update() {
  pip="$1"
  __exists "$pip" && "$pip" install --user -U $("$pip" | awk '!/Package|---/{ print $1}')
}

while true; do __sudo -v; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
if [ "$(uname -s)" = "Darwin" ]
then
  if [ -n "$mac" ]
  then
    #printf "y\nd\n"|__sudo port reclaim
    __sudo port selfupdate
    port outdated
    __sudo port -u upgrade outdated
    softwareupdate -i -a --verbose
    __exists mas && mas upgrade
    mac-update
  fi
elif [ "$(uname -s)" = "Linux" ]
then
  __exists apt-get && __sudo apt-get update
  __exists apt-get && __sudo apt-get dist-upgrade
  __exists yum && __sudo yum upgrade
  __exists pacman && __sudo pacman -Syu
  __exists emerge && __sudo emerge --update --deep world
else
  if [ -n "$freebsd" ]
  then
    fbsd-rebuild
    __sudo pkg upgrade
    #for jid in $(jls jid); do __sudo pkg -j $jid upgrade -y ; done
    #for jid in $(jls jid); do __sudo pkg -j $jid autoremove ; done
  fi
fi
__exists gem && gem update --user-install
__exists npm && npm -g update
if [ -z "$freebsd" ]
then
  # FreeBSD's apm is for power management
  __exists apm && apm update --no-confirm
fi

_pip_update pip
for v in 3.6 3.7 3.8 3.9
do
  _pip_update pip-${v}
  _pip_update pip${v}
done

#cpan -u
if __exists vim
then
  vim -i NONE +PlugUpgrade +qa
  (cd ~/.conf && git commit -m "[vim] Update VimPlug config" vim/home/autoload/plug.vim && git push)
  vim -i NONE +PlugUpdate +PlugClean! +qa
fi
if __exists rustup
then
  rustup update
  rustup self update
fi
if __exists cargo
then
  cargo search # update registry
fi
if __exits stack
then
  stack upgrade
  stack update
fi
__exists R && R --quiet -e 'options(warn = 0); update.packages(ask = FALSE)'
if __exists pkgin
then
  __sudo pkgin -y update
  __sudo pkgin -y full-upgrade
fi
for lua in luarocks luarocks-5.3
do
  __exists lua && "$lua" install --local $("$lua" list --porcelain --outdated |cut -d '	' -f 1)
done
