#!/bin/sh

SANITZERS="address \
  alignment \
  bool \
  bounds \
  enum \
  float-cast-overflow \
  float-divide-by-zero \
  integer-divide-by-zero \
  nonnull-attribute \
  null \
  nullability-arg \
  nullability-assign \
  nullability-return \
  object-size \
  pointer-overflow \
  return \
  returns-nonnull-attribute \
  shift \
  unreachable \
  unsigned-integer-overflow \
  vla-bound \
  vptr
"

WARNS="-Weverything
-Wno-missing-noreturn
-Wno-c11-extensions
-Wno-nullability-extension
-Wno-macro-redefined
-Wno-padded
-Wno-vla
-Wno-reserved-id-macro
"

SANITZERS="$(printf "$SANITZERS" | sed 's/   /,/g')"

exec clang \
  $WARNS \
  -fsanitize="$SANITZERS" \
  -flto \
  -fwhole-program-vtables \
  -fstrict-vtable-pointers \
  -fdiagnostics-show-category=name \
  -fdiagnostics-show-template-tree \
  -D_CONST_X_STRING \
  -D_FORTIFY_SOURCE=2 \
  -g \
  "$@"
