#!/bin/sh

# -fsanitize=memory,thread
${CC:-clang} -fsanitize=alignment,bool,bounds,enum,float-cast-overflow,float-divide-by-zero,integer-divide-by-zero,nonnull-attribute,null,nullability-arg,nullability-assign,nullability-return,object-size,pointer-overflow,return,returns-nonnull-attribute,shift,signed-integer-overflow,unreachable,unsigned-integer-overflow,vla-bound,vptr,address -flto -fwhole-program-vtables -fstrict-vtable-pointers -Weverything --pedantic -fdiagnostics-show-category=name -fdiagnostics-show-template-tree -g "$@"
